### ISSUE TITLE
动态创建的对象上，无法正常调用 filter 方法

### ISSUE THREAD

**Issue by miller-lee** [zdhxiong/mdui.jq#1]
> 版本 JQ 1.0.0
环境 Cent Browser 版本 3.8.5.69（正式版本） （32 位） (Chromium 71.0.3578.98)

例如 `$$("<div id='d1'></div><div id='d2'></div>").filter("#d2")`
返回 `JQ {length: 0}`

**Comment by miller-lee** [comment]
应该是这里的问题 [$.js : 49](https://github.com/zdhxiong/mdui.JQ/blob/2952ede12782bcf49f6374cb1d563d11afe815a3/src/%24.js#L49)

**Comment by zdhxiong** [comment]
2.0 中已修复
